import os
import psycopg2
from psycopg2.extras import RealDictCursor
from datetime import date, datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Database connection parameters
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASS = os.getenv("DB_PASS")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")

def get_connection():
    return psycopg2.connect(
        dbname=DB_NAME,
        user=DB_USER,
        password=DB_PASS,
        host=DB_HOST,
        port=DB_PORT
    )

def format_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, (date, datetime)):
        return f"'{value}'"
    if isinstance(value, str):
        # Escape single quotes
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
    return str(value)

def export_table(cur, table_name, output_file):
    print(f"Exporting {table_name}...")
    cur.execute(f"SELECT * FROM {table_name}")
    rows = cur.fetchall()
    
    if not rows:
        return

    # Get column names
    columns = [desc[0] for desc in cur.description]
    cols_str = ", ".join(columns)

    output_file.write(f"\n-- Data for {table_name}\n")
    
    for row in rows:
        values = [format_value(row[col]) for col in columns]
        vals_str = ", ".join(values)
        sql = f"INSERT INTO {table_name} ({cols_str}) VALUES ({vals_str}) ON CONFLICT DO NOTHING;\n"
        output_file.write(sql)

def main():
    output_filename = "library_data_backup.sql"
    
    try:
        conn = get_connection()
        cur = conn.cursor(cursor_factory=RealDictCursor)
        
        with open(output_filename, "w", encoding="utf-8") as f:
            f.write("-- Library Data Backup\n")
            f.write("-- Generated by export_library_data.py\n\n")
            
            # Export in order of dependencies
            export_table(cur, "books", f)
            export_table(cur, "book_items", f)
            export_table(cur, "borrowing_records", f)
            
        print(f"\nSukses! Data berhasil diexport ke file: {output_filename}")
        print("Silakan buka file tersebut, copy isinya, dan jalankan di Query Tool server Anda.")
        
    except Exception as e:
        print(f"Error: {e}")
    finally:
        if 'cur' in locals():
            cur.close()
        if 'conn' in locals():
            conn.close()

if __name__ == "__main__":
    main()
